// AUTO-GENERATED by generate_demo.py — 직접 편집 금지. 재생성: python demo/generate_demo.py
window.LAKE_DEMO = {
  "generatedAt": "2026-07-06 14:45",
  "projectKey": "LAKE",
  "seed": 42,
  "timeline": {
    "start": "2026-01-05",
    "end": "2026-12-15"
  },
  "modules": [
    {
      "id": "M1",
      "name": "ETL"
    },
    {
      "id": "M2",
      "name": "Catalog"
    },
    {
      "id": "M3",
      "name": "Runtime"
    },
    {
      "id": "M4",
      "name": "Workbench"
    },
    {
      "id": "M5",
      "name": "SDK"
    },
    {
      "id": "M6",
      "name": "DevOps"
    },
    {
      "id": "M7",
      "name": "Observability"
    }
  ],
  "epics": {
    "E-ETL-CDC": {
      "key": "E-ETL-CDC",
      "name": "CDC 실시간 파이프라인",
      "doneSp": 11.0,
      "totalSp": 19.0,
      "mockSp": 8.0,
      "progressPct": 57.9,
      "countedIssues": 4,
      "excludedIssues": 0,
      "stories": [
        {
          "key": "E-ETL-CDC-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 2,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-ETL-CDC-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-ETL-CDC-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-ETL-CDC-4",
          "summary": "[Mock] 추정 작업 #4",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    },
    "E-ETL-BATCH": {
      "key": "E-ETL-BATCH",
      "name": "배치 적재 프레임워크",
      "doneSp": 0.0,
      "totalSp": 18.0,
      "mockSp": 8.0,
      "progressPct": 0.0,
      "countedIssues": 4,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-ETL-BATCH-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 8,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-ETL-BATCH-2",
          "summary": "[Mock] 추정 작업 #2",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-ETL-BATCH-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 2,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-ETL-BATCH-4",
          "summary": "[Mock] 추정 작업 #4",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-ETL-BATCH-5",
          "summary": "버그 수정 #5",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "inprogress",
          "labels": []
        }
      ]
    },
    "E-EVENT-SCHEMA": {
      "key": "E-EVENT-SCHEMA",
      "name": "이벤트 스트림 스키마",
      "doneSp": 5.0,
      "totalSp": 18.0,
      "mockSp": 3.0,
      "progressPct": 27.8,
      "countedIssues": 5,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-EVENT-SCHEMA-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 1,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-EVENT-SCHEMA-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 5,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-EVENT-SCHEMA-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 8,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-EVENT-SCHEMA-4",
          "summary": "[Mock] 추정 작업 #4",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-EVENT-SCHEMA-5",
          "summary": "버그 수정 #5",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-EVENT-SCHEMA-6",
          "summary": "작업 #6",
          "type": "Story",
          "sp": 1,
          "statusCategory": "todo",
          "labels": []
        }
      ]
    },
    "E-CAT-REGISTRY": {
      "key": "E-CAT-REGISTRY",
      "name": "카탈로그 레지스트리",
      "doneSp": 12.0,
      "totalSp": 28.0,
      "mockSp": 13.0,
      "progressPct": 42.9,
      "countedIssues": 6,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-CAT-REGISTRY-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-CAT-REGISTRY-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-CAT-REGISTRY-3",
          "summary": "버그 수정 #3",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-CAT-REGISTRY-4",
          "summary": "[Mock] 추정 작업 #4",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-CAT-REGISTRY-5",
          "summary": "[Mock] 추정 작업 #5",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-CAT-REGISTRY-6",
          "summary": "작업 #6",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-CAT-REGISTRY-7",
          "summary": "작업 #7",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        }
      ]
    },
    "E-META-SCHEMA": {
      "key": "E-META-SCHEMA",
      "name": "공통 메타데이터 스키마",
      "doneSp": 0.0,
      "totalSp": 27.0,
      "mockSp": 5.0,
      "progressPct": 0.0,
      "countedIssues": 6,
      "excludedIssues": 0,
      "stories": [
        {
          "key": "E-META-SCHEMA-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 1,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-META-SCHEMA-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-META-SCHEMA-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 5,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-META-SCHEMA-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-META-SCHEMA-5",
          "summary": "작업 #5",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-META-SCHEMA-6",
          "summary": "[Mock] 추정 작업 #6",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    },
    "E-LINEAGE": {
      "key": "E-LINEAGE",
      "name": "데이터 리니지 추적",
      "doneSp": 0.0,
      "totalSp": 6.0,
      "mockSp": 0.0,
      "progressPct": 0.0,
      "countedIssues": 3,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-LINEAGE-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 2,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-LINEAGE-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 1,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-LINEAGE-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-LINEAGE-4",
          "summary": "버그 수정 #4",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "done",
          "labels": []
        }
      ]
    },
    "E-RT-ENGINE": {
      "key": "E-RT-ENGINE",
      "name": "쿼리 실행 엔진",
      "doneSp": 8.0,
      "totalSp": 39.0,
      "mockSp": 8.0,
      "progressPct": 20.5,
      "countedIssues": 8,
      "excludedIssues": 0,
      "stories": [
        {
          "key": "E-RT-ENGINE-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-RT-ENGINE-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 5,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-RT-ENGINE-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-RT-ENGINE-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 1,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-RT-ENGINE-5",
          "summary": "작업 #5",
          "type": "Story",
          "sp": 8,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-RT-ENGINE-6",
          "summary": "[Mock] 추정 작업 #6",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-RT-ENGINE-7",
          "summary": "작업 #7",
          "type": "Story",
          "sp": 8,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-RT-ENGINE-8",
          "summary": "작업 #8",
          "type": "Story",
          "sp": 3,
          "statusCategory": "inprogress",
          "labels": []
        }
      ]
    },
    "E-RT-CACHE": {
      "key": "E-RT-CACHE",
      "name": "결과 캐시/가속",
      "doneSp": 16.0,
      "totalSp": 24.0,
      "mockSp": 0.0,
      "progressPct": 66.7,
      "countedIssues": 3,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-RT-CACHE-1",
          "summary": "버그 수정 #1",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-RT-CACHE-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 8,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-RT-CACHE-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-RT-CACHE-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        }
      ]
    },
    "E-API-GW": {
      "key": "E-API-GW",
      "name": "공통 API 게이트웨이",
      "doneSp": 4.0,
      "totalSp": 22.0,
      "mockSp": 11.0,
      "progressPct": 18.2,
      "countedIssues": 7,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-API-GW-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 2,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-API-GW-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-API-GW-3",
          "summary": "[Mock] 추정 작업 #3",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-API-GW-4",
          "summary": "버그 수정 #4",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-API-GW-5",
          "summary": "작업 #5",
          "type": "Story",
          "sp": 2,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-API-GW-6",
          "summary": "작업 #6",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-API-GW-7",
          "summary": "작업 #7",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-API-GW-8",
          "summary": "[Mock] 추정 작업 #8",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    },
    "E-WB-NOTEBOOK": {
      "key": "E-WB-NOTEBOOK",
      "name": "노트북/쿼리 워크스페이스",
      "doneSp": 4.0,
      "totalSp": 23.0,
      "mockSp": 16.0,
      "progressPct": 17.4,
      "countedIssues": 7,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-WB-NOTEBOOK-1",
          "summary": "[Mock] 추정 작업 #1",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-WB-NOTEBOOK-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 2,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-WB-NOTEBOOK-3",
          "summary": "[Mock] 추정 작업 #3",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-WB-NOTEBOOK-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-WB-NOTEBOOK-5",
          "summary": "작업 #5",
          "type": "Story",
          "sp": 1,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-WB-NOTEBOOK-6",
          "summary": "버그 수정 #6",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-WB-NOTEBOOK-7",
          "summary": "작업 #7",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-WB-NOTEBOOK-8",
          "summary": "[Mock] 추정 작업 #8",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    },
    "E-WB-DASH": {
      "key": "E-WB-DASH",
      "name": "대시보드/시각화",
      "doneSp": 2.0,
      "totalSp": 7.0,
      "mockSp": 3.0,
      "progressPct": 28.6,
      "countedIssues": 4,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-WB-DASH-1",
          "summary": "[Mock] 추정 작업 #1",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-WB-DASH-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 1,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-WB-DASH-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 1,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-WB-DASH-4",
          "summary": "버그 수정 #4",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-WB-DASH-5",
          "summary": "작업 #5",
          "type": "Story",
          "sp": 2,
          "statusCategory": "done",
          "labels": []
        }
      ]
    },
    "E-SDK-PY": {
      "key": "E-SDK-PY",
      "name": "Python SDK",
      "doneSp": 1.0,
      "totalSp": 17.0,
      "mockSp": 8.0,
      "progressPct": 5.9,
      "countedIssues": 4,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-SDK-PY-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-SDK-PY-2",
          "summary": "버그 수정 #2",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-SDK-PY-3",
          "summary": "[Mock] 추정 작업 #3",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-SDK-PY-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-SDK-PY-5",
          "summary": "[Mock] 추정 작업 #5",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    },
    "E-SDK-JAVA": {
      "key": "E-SDK-JAVA",
      "name": "JVM SDK",
      "doneSp": 28.0,
      "totalSp": 28.0,
      "mockSp": 0.0,
      "progressPct": 100.0,
      "countedIssues": 6,
      "excludedIssues": 2,
      "stories": [
        {
          "key": "E-SDK-JAVA-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-SDK-JAVA-2",
          "summary": "버그 수정 #2",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-SDK-JAVA-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-SDK-JAVA-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-SDK-JAVA-5",
          "summary": "버그 수정 #5",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-SDK-JAVA-6",
          "summary": "작업 #6",
          "type": "Story",
          "sp": 2,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-SDK-JAVA-7",
          "summary": "작업 #7",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-SDK-JAVA-8",
          "summary": "작업 #8",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        }
      ]
    },
    "E-AUTH-MODEL": {
      "key": "E-AUTH-MODEL",
      "name": "인증/권한 모델",
      "doneSp": 6.0,
      "totalSp": 27.0,
      "mockSp": 18.0,
      "progressPct": 22.2,
      "countedIssues": 7,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-AUTH-MODEL-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-AUTH-MODEL-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 2,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-AUTH-MODEL-3",
          "summary": "[Mock] 추정 작업 #3",
          "type": "Story",
          "sp": 8,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-AUTH-MODEL-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-AUTH-MODEL-5",
          "summary": "버그 수정 #5",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-AUTH-MODEL-6",
          "summary": "작업 #6",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-AUTH-MODEL-7",
          "summary": "[Mock] 추정 작업 #7",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-AUTH-MODEL-8",
          "summary": "[Mock] 추정 작업 #8",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    },
    "E-DO-IAC": {
      "key": "E-DO-IAC",
      "name": "인프라 IaC 표준화",
      "doneSp": 16.0,
      "totalSp": 19.0,
      "mockSp": 0.0,
      "progressPct": 84.2,
      "countedIssues": 5,
      "excludedIssues": 0,
      "stories": [
        {
          "key": "E-DO-IAC-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 2,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-DO-IAC-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-DO-IAC-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 8,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-DO-IAC-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 3,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-DO-IAC-5",
          "summary": "작업 #5",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        }
      ]
    },
    "E-DO-CICD": {
      "key": "E-DO-CICD",
      "name": "CI/CD 파이프라인",
      "doneSp": 4.0,
      "totalSp": 25.0,
      "mockSp": 13.0,
      "progressPct": 16.0,
      "countedIssues": 7,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-DO-CICD-1",
          "summary": "[Mock] 추정 작업 #1",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-DO-CICD-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-DO-CICD-3",
          "summary": "[Mock] 추정 작업 #3",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-DO-CICD-4",
          "summary": "[Mock] 추정 작업 #4",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-DO-CICD-5",
          "summary": "버그 수정 #5",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-DO-CICD-6",
          "summary": "작업 #6",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-DO-CICD-7",
          "summary": "작업 #7",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-DO-CICD-8",
          "summary": "작업 #8",
          "type": "Story",
          "sp": 5,
          "statusCategory": "inprogress",
          "labels": []
        }
      ]
    },
    "E-OB-METRICS": {
      "key": "E-OB-METRICS",
      "name": "메트릭/모니터링 스택",
      "doneSp": 3.0,
      "totalSp": 10.0,
      "mockSp": 6.0,
      "progressPct": 30.0,
      "countedIssues": 4,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-OB-METRICS-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 3,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-OB-METRICS-2",
          "summary": "[Mock] 추정 작업 #2",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        },
        {
          "key": "E-OB-METRICS-3",
          "summary": "버그 수정 #3",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-OB-METRICS-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 1,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-OB-METRICS-5",
          "summary": "[Mock] 추정 작업 #5",
          "type": "Story",
          "sp": 3,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    },
    "E-OB-LOG": {
      "key": "E-OB-LOG",
      "name": "로그/트레이싱",
      "doneSp": 8.0,
      "totalSp": 23.0,
      "mockSp": 5.0,
      "progressPct": 34.8,
      "countedIssues": 7,
      "excludedIssues": 1,
      "stories": [
        {
          "key": "E-OB-LOG-1",
          "summary": "작업 #1",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-OB-LOG-2",
          "summary": "작업 #2",
          "type": "Story",
          "sp": 2,
          "statusCategory": "todo",
          "labels": []
        },
        {
          "key": "E-OB-LOG-3",
          "summary": "작업 #3",
          "type": "Story",
          "sp": 5,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-OB-LOG-4",
          "summary": "작업 #4",
          "type": "Story",
          "sp": 3,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-OB-LOG-5",
          "summary": "작업 #5",
          "type": "Story",
          "sp": 2,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-OB-LOG-6",
          "summary": "작업 #6",
          "type": "Story",
          "sp": 1,
          "statusCategory": "done",
          "labels": []
        },
        {
          "key": "E-OB-LOG-7",
          "summary": "버그 수정 #7",
          "type": "Bug",
          "sp": 0,
          "statusCategory": "inprogress",
          "labels": []
        },
        {
          "key": "E-OB-LOG-8",
          "summary": "[Mock] 추정 작업 #8",
          "type": "Story",
          "sp": 5,
          "statusCategory": "todo",
          "labels": [
            "mock"
          ]
        }
      ]
    }
  },
  "wbs": [
    {
      "id": "W-ETL-1",
      "moduleId": "M1",
      "name": "실시간 수집 체계",
      "start": "2026-01-06",
      "end": "2026-05-29",
      "progressPct": 45.9,
      "effectiveSp": 18.6,
      "epics": [
        {
          "epicKey": "E-ETL-CDC",
          "epicName": "CDC 실시간 파이프라인",
          "weight": 0.6,
          "epicPct": 57.9,
          "contribution": 34.7,
          "start": "2026-01-13",
          "end": "2026-05-08"
        },
        {
          "epicKey": "E-EVENT-SCHEMA",
          "epicName": "이벤트 스트림 스키마",
          "weight": 0.4,
          "epicPct": 27.8,
          "contribution": 11.1,
          "start": "2026-02-03",
          "end": "2026-05-22"
        }
      ]
    },
    {
      "id": "W-ETL-2",
      "moduleId": "M1",
      "name": "배치 적재 표준화",
      "start": "2026-03-02",
      "end": "2026-08-14",
      "progressPct": 0.0,
      "effectiveSp": 20.7,
      "epics": [
        {
          "epicKey": "E-ETL-BATCH",
          "epicName": "배치 적재 프레임워크",
          "weight": 0.7,
          "epicPct": 0.0,
          "contribution": 0.0,
          "start": "2026-03-10",
          "end": "2026-07-21"
        },
        {
          "epicKey": "E-META-SCHEMA",
          "epicName": "공통 메타데이터 스키마",
          "weight": 0.3,
          "epicPct": 0.0,
          "contribution": 0.0,
          "start": "2026-04-04",
          "end": "2026-08-06"
        }
      ]
    },
    {
      "id": "W-CAT-1",
      "moduleId": "M2",
      "name": "카탈로그 구축",
      "start": "2026-02-02",
      "end": "2026-07-31",
      "progressPct": 25.7,
      "effectiveSp": 27.6,
      "epics": [
        {
          "epicKey": "E-CAT-REGISTRY",
          "epicName": "카탈로그 레지스트리",
          "weight": 0.6,
          "epicPct": 42.9,
          "contribution": 25.7,
          "start": "2026-02-10",
          "end": "2026-07-05"
        },
        {
          "epicKey": "E-META-SCHEMA",
          "epicName": "공통 메타데이터 스키마",
          "weight": 0.4,
          "epicPct": 0.0,
          "contribution": 0.0,
          "start": "2026-03-09",
          "end": "2026-07-23"
        }
      ]
    },
    {
      "id": "W-CAT-2",
      "moduleId": "M2",
      "name": "리니지 연동",
      "start": "2026-05-04",
      "end": "2026-10-30",
      "progressPct": 0.0,
      "effectiveSp": 16.5,
      "epics": [
        {
          "epicKey": "E-LINEAGE",
          "epicName": "데이터 리니지 추적",
          "weight": 0.5,
          "epicPct": 0.0,
          "contribution": 0.0,
          "start": "2026-05-12",
          "end": "2026-10-04"
        },
        {
          "epicKey": "E-META-SCHEMA",
          "epicName": "공통 메타데이터 스키마",
          "weight": 0.5,
          "epicPct": 0.0,
          "contribution": 0.0,
          "start": "2026-06-08",
          "end": "2026-10-22"
        }
      ]
    },
    {
      "id": "W-RT-1",
      "moduleId": "M3",
      "name": "쿼리 실행 엔진",
      "start": "2026-01-19",
      "end": "2026-06-30",
      "progressPct": 22.7,
      "effectiveSp": 32.7,
      "epics": [
        {
          "epicKey": "E-RT-ENGINE",
          "epicName": "쿼리 실행 엔진",
          "weight": 0.7,
          "epicPct": 20.5,
          "contribution": 14.3,
          "start": "2026-01-27",
          "end": "2026-06-06"
        },
        {
          "epicKey": "E-EVENT-SCHEMA",
          "epicName": "이벤트 스트림 스키마",
          "weight": 0.3,
          "epicPct": 27.8,
          "contribution": 8.3,
          "start": "2026-02-20",
          "end": "2026-06-22"
        }
      ]
    },
    {
      "id": "W-RT-2",
      "moduleId": "M3",
      "name": "쿼리 가속",
      "start": "2026-04-01",
      "end": "2026-09-30",
      "progressPct": 48.2,
      "effectiveSp": 30.0,
      "epics": [
        {
          "epicKey": "E-RT-CACHE",
          "epicName": "결과 캐시/가속",
          "weight": 0.6,
          "epicPct": 66.7,
          "contribution": 40.0,
          "start": "2026-04-10",
          "end": "2026-09-03"
        },
        {
          "epicKey": "E-RT-ENGINE",
          "epicName": "쿼리 실행 엔진",
          "weight": 0.4,
          "epicPct": 20.5,
          "contribution": 8.2,
          "start": "2026-05-07",
          "end": "2026-09-21"
        }
      ]
    },
    {
      "id": "W-RT-3",
      "moduleId": "M3",
      "name": "API 게이트웨이",
      "start": "2026-06-01",
      "end": "2026-11-30",
      "progressPct": 18.7,
      "effectiveSp": 25.4,
      "epics": [
        {
          "epicKey": "E-API-GW",
          "epicName": "공통 API 게이트웨이",
          "weight": 0.8,
          "epicPct": 18.2,
          "contribution": 14.6,
          "start": "2026-06-10",
          "end": "2026-11-03"
        },
        {
          "epicKey": "E-RT-ENGINE",
          "epicName": "쿼리 실행 엔진",
          "weight": 0.2,
          "epicPct": 20.5,
          "contribution": 4.1,
          "start": "2026-07-07",
          "end": "2026-11-21"
        }
      ]
    },
    {
      "id": "W-WB-1",
      "moduleId": "M4",
      "name": "쿼리 워크스페이스",
      "start": "2026-03-16",
      "end": "2026-09-15",
      "progressPct": 17.6,
      "effectiveSp": 22.7,
      "epics": [
        {
          "epicKey": "E-WB-NOTEBOOK",
          "epicName": "노트북/쿼리 워크스페이스",
          "weight": 0.7,
          "epicPct": 17.4,
          "contribution": 12.2,
          "start": "2026-03-25",
          "end": "2026-08-19"
        },
        {
          "epicKey": "E-API-GW",
          "epicName": "공통 API 게이트웨이",
          "weight": 0.3,
          "epicPct": 18.2,
          "contribution": 5.5,
          "start": "2026-04-21",
          "end": "2026-09-06"
        }
      ]
    },
    {
      "id": "W-WB-2",
      "moduleId": "M4",
      "name": "대시보드",
      "start": "2026-06-15",
      "end": "2026-12-15",
      "progressPct": 26.0,
      "effectiveSp": 15.0,
      "epics": [
        {
          "epicKey": "E-WB-DASH",
          "epicName": "대시보드/시각화",
          "weight": 0.6,
          "epicPct": 28.6,
          "contribution": 17.2,
          "start": "2026-06-24",
          "end": "2026-11-18"
        },
        {
          "epicKey": "E-AUTH-MODEL",
          "epicName": "인증/권한 모델",
          "weight": 0.4,
          "epicPct": 22.2,
          "contribution": 8.9,
          "start": "2026-07-21",
          "end": "2026-12-06"
        }
      ]
    },
    {
      "id": "W-SDK-1",
      "moduleId": "M5",
      "name": "Python SDK",
      "start": "2026-02-16",
      "end": "2026-07-17",
      "progressPct": 9.6,
      "effectiveSp": 18.5,
      "epics": [
        {
          "epicKey": "E-SDK-PY",
          "epicName": "Python SDK",
          "weight": 0.7,
          "epicPct": 5.9,
          "contribution": 4.1,
          "start": "2026-02-23",
          "end": "2026-06-25"
        },
        {
          "epicKey": "E-API-GW",
          "epicName": "공통 API 게이트웨이",
          "weight": 0.3,
          "epicPct": 18.2,
          "contribution": 5.5,
          "start": "2026-03-18",
          "end": "2026-07-10"
        }
      ]
    },
    {
      "id": "W-SDK-2",
      "moduleId": "M5",
      "name": "JVM SDK & 인증",
      "start": "2026-05-18",
      "end": "2026-11-13",
      "progressPct": 68.9,
      "effectiveSp": 27.6,
      "epics": [
        {
          "epicKey": "E-SDK-JAVA",
          "epicName": "JVM SDK",
          "weight": 0.6,
          "epicPct": 100.0,
          "contribution": 60.0,
          "start": "2026-05-26",
          "end": "2026-10-18"
        },
        {
          "epicKey": "E-AUTH-MODEL",
          "epicName": "인증/권한 모델",
          "weight": 0.4,
          "epicPct": 22.2,
          "contribution": 8.9,
          "start": "2026-06-22",
          "end": "2026-11-05"
        }
      ]
    },
    {
      "id": "W-DO-1",
      "moduleId": "M6",
      "name": "플랫폼 IaC",
      "start": "2026-01-05",
      "end": "2026-06-05",
      "progressPct": 59.4,
      "effectiveSp": 22.2,
      "epics": [
        {
          "epicKey": "E-DO-IAC",
          "epicName": "인프라 IaC 표준화",
          "weight": 0.6,
          "epicPct": 84.2,
          "contribution": 50.5,
          "start": "2026-01-12",
          "end": "2026-05-14"
        },
        {
          "epicKey": "E-AUTH-MODEL",
          "epicName": "인증/권한 모델",
          "weight": 0.4,
          "epicPct": 22.2,
          "contribution": 8.9,
          "start": "2026-02-04",
          "end": "2026-05-29"
        }
      ]
    },
    {
      "id": "W-DO-2",
      "moduleId": "M6",
      "name": "CI/CD",
      "start": "2026-04-06",
      "end": "2026-10-09",
      "progressPct": 36.5,
      "effectiveSp": 23.2,
      "epics": [
        {
          "epicKey": "E-DO-CICD",
          "epicName": "CI/CD 파이프라인",
          "weight": 0.7,
          "epicPct": 16.0,
          "contribution": 11.2,
          "start": "2026-04-15",
          "end": "2026-09-12"
        },
        {
          "epicKey": "E-DO-IAC",
          "epicName": "인프라 IaC 표준화",
          "weight": 0.3,
          "epicPct": 84.2,
          "contribution": 25.3,
          "start": "2026-05-13",
          "end": "2026-09-30"
        }
      ]
    },
    {
      "id": "W-OB-1",
      "moduleId": "M7",
      "name": "모니터링 스택",
      "start": "2026-03-02",
      "end": "2026-08-31",
      "progressPct": 18.0,
      "effectiveSp": 16.8,
      "epics": [
        {
          "epicKey": "E-OB-METRICS",
          "epicName": "메트릭/모니터링 스택",
          "weight": 0.6,
          "epicPct": 30.0,
          "contribution": 18.0,
          "start": "2026-03-11",
          "end": "2026-08-04"
        },
        {
          "epicKey": "E-META-SCHEMA",
          "epicName": "공통 메타데이터 스키마",
          "weight": 0.4,
          "epicPct": 0.0,
          "contribution": 0.0,
          "start": "2026-04-07",
          "end": "2026-08-22"
        }
      ]
    },
    {
      "id": "W-OB-2",
      "moduleId": "M7",
      "name": "로그/리니지",
      "start": "2026-06-01",
      "end": "2026-12-11",
      "progressPct": 17.4,
      "effectiveSp": 14.5,
      "epics": [
        {
          "epicKey": "E-OB-LOG",
          "epicName": "로그/트레이싱",
          "weight": 0.5,
          "epicPct": 34.8,
          "contribution": 17.4,
          "start": "2026-06-10",
          "end": "2026-11-13"
        },
        {
          "epicKey": "E-LINEAGE",
          "epicName": "데이터 리니지 추적",
          "weight": 0.5,
          "epicPct": 0.0,
          "contribution": 0.0,
          "start": "2026-07-09",
          "end": "2026-12-02"
        }
      ]
    }
  ],
  "rollup": {
    "pmo": {
      "progressPct": 29.5,
      "rawDoneSp": 128.0,
      "rawTotalSp": 380.0,
      "rawMockSp": 125.0,
      "moduleCount": 7,
      "wbsCount": 15,
      "epicCount": 18
    },
    "modules": [
      {
        "id": "M1",
        "name": "ETL",
        "progressPct": 21.7,
        "effectiveSp": 39.3,
        "start": "2026-01-06",
        "end": "2026-08-14",
        "wbsIds": [
          "W-ETL-1",
          "W-ETL-2"
        ],
        "rawDoneSp": 16.0,
        "rawTotalSp": 82.0,
        "rawMockSp": 24.0
      },
      {
        "id": "M2",
        "name": "Catalog",
        "progressPct": 16.1,
        "effectiveSp": 44.1,
        "start": "2026-02-02",
        "end": "2026-10-30",
        "wbsIds": [
          "W-CAT-1",
          "W-CAT-2"
        ],
        "rawDoneSp": 12.0,
        "rawTotalSp": 61.0,
        "rawMockSp": 18.0
      },
      {
        "id": "M3",
        "name": "Runtime",
        "progressPct": 30.2,
        "effectiveSp": 88.1,
        "start": "2026-01-19",
        "end": "2026-11-30",
        "wbsIds": [
          "W-RT-1",
          "W-RT-2",
          "W-RT-3"
        ],
        "rawDoneSp": 33.0,
        "rawTotalSp": 103.0,
        "rawMockSp": 22.0
      },
      {
        "id": "M4",
        "name": "Workbench",
        "progressPct": 20.9,
        "effectiveSp": 37.7,
        "start": "2026-03-16",
        "end": "2026-12-15",
        "wbsIds": [
          "W-WB-1",
          "W-WB-2"
        ],
        "rawDoneSp": 16.0,
        "rawTotalSp": 79.0,
        "rawMockSp": 48.0
      },
      {
        "id": "M5",
        "name": "SDK",
        "progressPct": 45.1,
        "effectiveSp": 46.1,
        "start": "2026-02-16",
        "end": "2026-11-13",
        "wbsIds": [
          "W-SDK-1",
          "W-SDK-2"
        ],
        "rawDoneSp": 39.0,
        "rawTotalSp": 94.0,
        "rawMockSp": 37.0
      },
      {
        "id": "M6",
        "name": "DevOps",
        "progressPct": 47.7,
        "effectiveSp": 45.4,
        "start": "2026-01-05",
        "end": "2026-10-09",
        "wbsIds": [
          "W-DO-1",
          "W-DO-2"
        ],
        "rawDoneSp": 26.0,
        "rawTotalSp": 71.0,
        "rawMockSp": 31.0
      },
      {
        "id": "M7",
        "name": "Observability",
        "progressPct": 17.7,
        "effectiveSp": 31.3,
        "start": "2026-03-02",
        "end": "2026-12-11",
        "wbsIds": [
          "W-OB-1",
          "W-OB-2"
        ],
        "rawDoneSp": 11.0,
        "rawTotalSp": 66.0,
        "rawMockSp": 16.0
      }
    ]
  }
};
